inputs:
  benchmarks: "./resources/inputs/progs-test.txt"
  flags: "./resources/inputs/flags-test.txt"

number-of-executions: 10

temperature:
  baseline: 40
  # cooldown-interval: 0.

outputs:
  results: "./data/results.csv"
  logs: "./data/logs.txt"
