inputs:
  # benchmarks: "./resources/inputs/progs-all.txt"
  benchmarks: "./resources/inputs/progs.txt"
  flags: "./resources/inputs/flags_O2.txt"
  # flags: "./resources/inputs/flags-test.txt"

base-flags: "-O2"
number-of-executions: 20

temperature:
  baseline: 65
  # cooldown-interval: 0.

outputs:
  results: "./data/results_65_2.csv"
  logs: "./data/logs_65_2.txt"
