inputs:
  # benchmarks: "./resources/inputs/progs-all.txt"
  benchmarks: "./resources/inputs/progs.txt"
  flags: "./resources/inputs/flags_O2.txt"
  # flags: "./resources/inputs/flags-test.txt"

base-flags: "-O2"
number-of-executions: 20

temperature:
  baseline: 45
  # cooldown-interval: 0.

outputs:
  results: "./data/results.csv"
  logs: "./data/logs.txt"
